// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2x5o9hvl2okA2tU3MePK2EFBmc-YuFQ',
    appId: '1:1039888718908:web:6caaa75b70bf024274f739',
    messagingSenderId: '1039888718908',
    projectId: 'water-supply-3f70f',
    authDomain: 'water-supply-3f70f.firebaseapp.com',
    storageBucket: 'water-supply-3f70f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkwvQv8jfAvS-z_48oTMxLg5AYzN99kkI',
    appId: '1:1039888718908:android:6cd196e50415f62c74f739',
    messagingSenderId: '1039888718908',
    projectId: 'water-supply-3f70f',
    storageBucket: 'water-supply-3f70f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmLN2xX6mjJPtDShc8tpH6dbkIfxc4Pwk',
    appId: '1:1039888718908:ios:4c8655495488741074f739',
    messagingSenderId: '1039888718908',
    projectId: 'water-supply-3f70f',
    storageBucket: 'water-supply-3f70f.appspot.com',
    iosBundleId: 'com.example.waterSupplyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmLN2xX6mjJPtDShc8tpH6dbkIfxc4Pwk',
    appId: '1:1039888718908:ios:4c8655495488741074f739',
    messagingSenderId: '1039888718908',
    projectId: 'water-supply-3f70f',
    storageBucket: 'water-supply-3f70f.appspot.com',
    iosBundleId: 'com.example.waterSupplyManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx2x5o9hvl2okA2tU3MePK2EFBmc-YuFQ',
    appId: '1:1039888718908:web:28dba9aafa3b3cf174f739',
    messagingSenderId: '1039888718908',
    projectId: 'water-supply-3f70f',
    authDomain: 'water-supply-3f70f.firebaseapp.com',
    storageBucket: 'water-supply-3f70f.appspot.com',
  );

}